### ISSUE TITLE
Repository organization

### ISSUE THREAD

**Issue by taxe10** [mlexchange/mlex_latent_explorer#15]
Currently, the repository needs some organization as detailed below:
- [x] Move [mlex_dimension_reduction_pca](https://github.com/runboj/mlex_dimension_reduction_pca) and [mlex_dimension_reduction_umap](https://github.com/runboj/mlex_dimension_reduction_umap) to [mlexchange](https://github.com/mlexchange)
- [x] Add `pyproject.toml` with requirements list and optional dependency group for dev (in frontend app and the 2 dimension reduction repos)
- [x] Move `Dockerfile` outside `docker` folder (in frontend app and the 2 dimension reduction repos)
- [x] Update README.md (in frontend app and the 2 dimension reduction repos)
- [ ] Add unit tests (for 1 callback within frontend app and the 2 dimension reduction repos)
- [x] Add GitHub action to check formatting and unit testing, similarly to: [test-lint.yml](https://github.com/mlexchange/mlex_highres_segmentation/blob/main/.github/workflows/test-lint.yml) (in frontend app and the 2 dimension reduction repos)

**Comment by dylanmcreynolds** [comment]
For what it's worth, Dash provides some built-in support for unit tests: https://dash.plotly.com/testing. I would read that document up until the section on end-to-end tests. In the remaining time that you have, I don't think we'll do more than test a single callback. However, that at least would give us the ability to test imports of modules and things like that.

I would also move the last two items in your list to the top, and get rid of requirements.txt, pushing the dependencies into pyproject.toml (with optional dependency group for [dev]. Doing this first will reduct the amount of rework we have to do on the other bullets.

**Comment by taxe10** [comment]
> For what it's worth, Dash provides some built-in support for unit tests: https://dash.plotly.com/testing. I would read that document up until the section on end-to-end tests. In the remaining time that you have, I don't think we'll do more than test a single callback. However, that at least would give us the ability to test imports of modules and things like that.
> 
> I would also move the last two items in Tanny's list to the top, and get rid of requirements.txt, pushing the dependencies into pyproject.toml (with optional dependency group for [dev]. Doing this first will reduct the amount of rework we have to do on the other bullets.

The list has been updated accordingly

**Comment by runboj** [comment]
For the third bullet point: "Move Dockerfile outside docker folder (in frontend app and the 2 dimension reduction repos)", after move Dockerfile outside docker folder, do we want to delete the requirements.txt file? since we have pyproject.toml? @taxe10

**Comment by runboj** [comment]
Will update readme after the confusion on the third bullet point resolved.

**Comment by runboj** [comment]
In PCA and UMAP repo, "pip install ." does not work:  error: Multiple top-level packages discovered in a flat-layout: ['data', 'docker', 'description'].

**Comment by dylanmcreynolds** [comment]
> do we want to delete the requirements.txt file? since we have pyproject.toml?

Yes, please.

**Comment by runboj** [comment]
Unit tests are added for PCA and UMAP. Cannot figure out how to do that for front end app at this point... working on it tho
